#!/bin/bash

setup(){
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az login  --use-device-code.
    echo "You're logged in"
}
//create storage account
storageAccount="uploads"
az storage account create --name $storageAccount --location "$location" --resource-group $resourceGroup --sku Standard_LRS --encryption-services blob

//fetching storage account name
//storageAccount=$()

// fetching storage account keys
az storage account keys list --resource-group $resourceGroup --account-name $storageAccount --query "[].value" -o tsv # returns both storage account key values
az storage account keys list --resource-group $resourceGroup --account-name $storageAccount --query "[0].value" -o tsv # returns a single storage account key value
accountKey=$(az storage account keys list --resource-group $resourceGroup --account-name $storageAccount --query "[0].value" -o tsv)

//storing creds in evironment variables
export AZURE_STORAGE_ACCOUNT=$storageAccount
export AZURE_STORAGE_KEY=$accountKey
