#!/bin/bash
# install/update azurecli
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash &>/dev/null
if command -v az &>/dev/null; then
    echo 'Azure Cli installtion is complete and upto-date!'
    export app_id
    export secret
    export tenant
    echo '************ENTER YOUR SERVICE PRINCIPAL CREDENTIALS************'
    read -p "application-id:" app_id
    read -p "password:" secret
    read -p "tenant:" tenant

    if [[ -z "$app_id" || -z "$secret" || -z "$tenant" ]]
    then
        echo "Error: provide all required values"
        exit 1
    else
        # logging into azure via service-principal
        if az login --service-principal -u $app_id -p $secret --tenant $tenant &>/dev/null; then
        # Get the service principal name
            sp_name=$(az ad sp show --id $app_id --query 'displayName' --output tsv)
            echo "Logged in successfully via $sp_name"
            exit 0
        else
            echo "Error: Service principal login failed"
            exit 1
        fi
    fi
else
    echo "Error installing Azure CLI."
fi